### ISSUE TITLE
please define what :: before a method is

### ISSUE THREAD

**Issue by Asilver-jpg** [learn-co-curriculum/orms-bringing-it-all-together#1]
While it has been stated that # and . can be placed before a method to show its intended use, this is the first time seeing :: and as such it can cause confusion without explanation. The work is still doable of course, but still can cause confusion for students.

**Comment by sylwiavargas** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
